extends RefCounted
class_name ColliderMasks

enum LAYERS  {
	NONE = 0,
	PLAYER = 1 << 2,
	ENEMY = 1 << 3,
	PLAYER_PROJECTILE = 1 << 4,
	ENEMY_PROJECTILE = 1 << 5,
	BOTH_PLAYER = PLAYER | PLAYER_PROJECTILE,
	BOTH_ENEMY = ENEMY | ENEMY_PROJECTILE,
}

enum TARGETS {
	NONE = 0,
	PLAYER = 1 << 2,
	ENEMY = 1 << 3,
	PLAYER_PROJECTILE = 1 << 4,
	ENEMY_PROJECTILE = 1 << 5,
	BOSS = 1 << 6,
	NEAREST_ENEMY = 1 << 7
}
